include:
    - project: 'lenra/environment'
      ref: master
      file: '/ci-cd/gitlab/lib/base.yml'
    - project: 'lenra/environment'
      ref: master
      file: '/ci-cd/gitlab/lib/docker.yml'

variables:
    VERSION_GETTER: flutter pub global run cider version

cache:
    paths:
        - ./build
        - ./pubspec.yaml

manage version:
    extends: .get version
    image: registry.gitlab.com/lenra/integration/docker-ci-flutter
    before_script:
        - flutter pub global run cider bump build    

build web prod:
    image: registry.gitlab.com/lenra/integration/docker-ci-flutter
    stage: build 
    script:
        - flutter pub get
        - flutter build web --release --target=./lib/main_prod.dart
    only:
        refs:
            - master

build web dev:
    image: registry.gitlab.com/lenra/integration/docker-ci-flutter
    stage: build
    script:
        - flutter pub get
        - flutter build web --release --target=./lib/main.dart
    except:
        refs:
            - master

dockerize web:
    extends: .build docker
    only:
        refs:
            - master
            - staging

dockerize web dev:
    extends: .build docker dev
