include:
  - project: "lenra/integration/ci/gitlab-ci"
    file: "/lib/base.yml"
  - project: "lenra/integration/ci/gitlab-ci"
    file: "/lib/docker.yml"
  - project: "lenra/integration/ci/gitlab-ci"
    file: "/lib/kubernetes.yml"
  - local: "/client/.gitlab-ci.yml"
  - local: "/server/.gitlab-ci.yml"
  - local: "/documentation/.gitlab-ci.yml"
  - local: "/k8s/.gitlab-ci.yml"

.subdir job:
  extends: .base job
  needs: []
  rules:
    - if: "$CI_COMMIT_BRANCH != $MAIN_BRANCH"
      changes: 
        - ${WORKDIR}/**/*

.subdir test job:
  rules:
    - if: "$CI_COMMIT_BRANCH == $MAIN_BRANCH"
      when: never
    - if: "$CI_COMMIT_BRANCH == $STAGING_BRANCH"
    - changes: 
        - ${WORKDIR}/**/*

manage version:
  variables:
    VERSION_GETTER: cat version
  extends: .get version
  needs: []

prepare release:
  extends: .prepare release
  variables:
    ISSUE_BASE_URL: https://lenra.atlassian.net/browse/
    REGEX_SUBJECT_PATTERN: ^((feature|bugfix|hotfix|ignore)\/)?(LENRA-[0-9]+)?(.*)$
  needs:
    - job: manage version
      artifacts: true

release:
  extends: .release
  needs:
    - job: manage version
      artifacts: true
    - job: prepare release
      artifacts: true
