name: lenra_components
description: Lenra's Flutter component library.
version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
