name: Flutter CI
on: push
jobs:
  Setup-Flutter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.2.3'
    - run: flutter pub get
    - run: flutter test