apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingressroute.yml
  - statefulset-postgres.yml
  - service-postgres.yml
# vars:
#   - name: LENRA_HOST
#     objref:
#       name: lenra-env
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.annotations.lenra_host
