apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: postgres-db
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11-alpine
          envFrom:
            - secretRef:
                name: lenra-postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-database
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: init-database
          configMap:
            name: init-database
