apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../client/k8s/base
  - ../../../server/k8s/base
  - ../../../documentation/k8s/base
  - ingressroute-redirect-https.yml
patchesStrategicMerge:
  - ingressroute.yml
